AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Naming/MethodName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
  AllowHeredoc: true
  AllowURI: true
  IgnoreCopDirectives: true
  TooLazyToSpecifyCount: true

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 100